spring.application.name=gestaovagas
spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_vagas
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update

security.token.secret=pJgnb1iBk4PjdFIIqAd2GF1wdUSdgL1ZQ9F84ogjQVQ

